=pod

=encoding utf8

=head1 Name

Tit::Manual – Guide and cookbook for L<Tit>.

=head1 Dispatch

…

=head1 Toys

Mention RFC:Toy? L<https://bitbucket.org/pangyre/rfc-toy>.

=head2 MiniWiki

 t/apps/mini-wiki.psgi
 t/lib/MiniWiki.pm

=head2 POD viewer

 t/apps/pod.psgi

=head2 Unicode Browser

=head1 Code Repository

L<http://github.com/pangyre/p5-tit>, private: L<https://bitbucket.org/pangyre/wren/>.

=head1 See Also

L<Plack::App::REST>, L<Plack::Middleware::REST>, L<Dancer2>,
L<Mojolicious>, L<Flea>, L<Kelp>, et cetera.

=head1 Author and License

See L<Tit>.

=cut
